[package]
name = "mu_proc_macros_lib"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["proc_macros_lib"]


[dependencies.proc_macros_lib]
name = "proc_macros_lib"
path = "./proc_macros_lib"

[dependencies]
